### ISSUE TITLE
After trying the same steps in the documentation I get this errors 

### ISSUE THREAD

**Issue by muhammmedkhattab** [0xIslamTaha/orchestrator-public-use-case#2]
**First Error:** 

Related to /mochawesome-report/mochawesome*.json No matched--> how it will match before the execution  
```bash
timeout --preserve-status 200m docker-compose -f docker-compose.yml run --name container_23113_chrome_0 cypress_container npx cypress run -b chrome --headless --spec cypress/integrationcypress/integration/Test1.spec.js
/bin/sh: timeout: command not found
generate the report ....
(node:89189) UnhandledPromiseRejectionWarning: Error: Pattern ./mochawesome-report/mochawesome/*.json matched no report files
    at /usr/local/lib/node_modules/@0xislamtaha/orchestrator/node_modules/mochawesome-merge/lib/index.js:14:11
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/@0xislamtaha/orchestrator/node_modules/mochawesome-merge/lib/utils.js:3:46
    at merge (/usr/local/lib/node_modules/@0xislamtaha/orchestrator/node_modules/mochawesome-merge/lib/index.js:82:17)
    at generateReport (/usr/local/lib/node_modules/@0xislamtaha/orchestrator/src/orchestrator.js:131:10)
    at afterPromises (/usr/local/lib/node_modules/@0xislamtaha/orchestrator/src/orchestrator.js:164:3)
    at /usr/local/lib/node_modules/@0xislamtaha/orchestrator/src/orchestrator.js:185:7
(Use `node --trace-warnings ...` to show where the warning was created)
(node:89189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:89189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Second Error:** 

if I added any .json file in the folder and not tests triggered 
```
START ORCHESTRATOR
timeout --preserve-status 200m docker-compose -f docker-compose.yml run --name container_62914_chrome_0 cypress_container npx cypress run -b chrome --headless --spec cypress/integrationcypress/integration/Test1.spec.js
/bin/sh: timeout: command not found
generate the report ....
------------------------- Exeuction Time -------------------------
All down in: 
orchestratorTime: 595.849ms
```

**Comment by 0xIslamTaha** [comment]
from the stack trace I can see that the main issue is `/bin/sh: timeout: command not found`. Your OS doesn't have `timeout` bash command. Could u post your OS specs?

**Comment by 0xIslamTaha** [comment]
closed as there is nothing to be done from my side
