### ISSUE TITLE
Can't star the execution using the command npx orchestrator...

### ISSUE THREAD

**Issue by msilesgap** [0xIslamTaha/orchestrator-public-use-case#4]
I'm getting the following error when I'm trying to execute the tests in parallel

moisessiles@msilesMacbook tests.cypress % npx orchestrator --config orchestrator.json
START ORCHESTRATOR
report does not exist, are you sure there is a json report in undefined path?
timeout --preserve-status 30m docker-compose -f docker-compose.yml run --name container_62639__0 cyddpress-container bash -c 'exit_code=0; npx cypress run -b chrome --headless --spec <TESTs NAMES> || exit_code=$? ; pkill -9 cypress ; exit $exit_code'
/bin/sh: timeout: command not found
generate the report ....
/Users/moisessiles/Downloads/Documents/Projects/project.tests.cypress/node_modules/mochawesome-merge/lib/index.js:49
  report.results.filter(r => r !== false)
                 ^

TypeError: Cannot read property 'filter' of undefined
    at /Users/moisessiles/Downloads/Documents/Projects/project.tests.cypress/node_modules/mochawesome-merge/lib/index.js:49:18
    at Array.map (<anonymous>)
    at /Users/moisessiles/Downloads/Documents/Projects/project.tests.cypress/node_modules/mochawesome-merge/lib/utils.js:3:46
    at merge (/Users/moisessiles/Downloads/Documents/Projects/project.tests.cypress/node_modules/mochawesome-merge/lib/index.js:84:18)
moisessiles@msilesMacbook tests.cypress %

**Comment by 0xIslamTaha** [comment]
@msilesgap 
u have couple of options here:
- u can add them the cypress.json file. 
- u can pass the env value [here](https://github.com/0xIslamTaha/orchestrator-public-use-case/blob/master/orchestrator.json#L5)

**Comment by 0xIslamTaha** [comment]
@msilesgap 
As I can see integrate Cypress with Allura is done in two steps:
- Install the required allura packages
- Add the env params to the cypress.json 

If u are doing your integration following the previous steps, then u can 100% integrate with Allura without any issues

But u have to give it a try, as maybe there is an underline overwrite or something like that.

**Comment by msilesgap** [comment]
@0xIslamTaha In your example all your spec files are inside example folder; what if there are multiple folders like this (folders inside folders with multiple specs)

- integration folder
-- dashboard folder
---spec1
---spec2
---spec3
---login folder
----spec1
----spec2
----specN

how should we write the specsHomePath and specsDockerPath

```
  "specsHomePath": "src/integration/",
  "specsDockerPath": "src/integration/",
```

or do we need to add ** at the end?

**Comment by msilesgap** [comment]
@0xIslamTaha I have tried these two options but the specs inside folders are not picked up, only the ones in the root of tests folder
```
 "specsHomePath": "src/integration/navigation/tests/**/*.spec.js",
"specsDockerPath": "src/integration/navigation/tests/**/*.spec.js",
```
or 

```
"specsHomePath": "src/integration/navigation/tests/**",
"specsDockerPath": "src/integration/navigation/tests/**",
```
