### ISSUE TITLE
Getting the below console errors

### ISSUE THREAD

**Issue by Surajbehera2017** [0xIslamTaha/orchestrator-public-use-case#8]
Thanks for the wonderful article, I cloned the repo but when running, I am getting the below error

[*] Start the cypress containers
[-] ~$ timeout --preserve-status 30m docker-compose  -p orchestator_project -f docker-compose.yml run --name container_85785__0 cypress-container bash -c 'exit_code=0; npx cypress run -b chrome --headless --spec cypress/integration/
examples/location.spec.js,cypress/integration/examples/test.spec4.js,cypress/integration/examples/local_storage.spec.js,cypress/integration/examples/test.spec2.js,cypress/integration/examples/cookies.spec.js,cypress/integration/exam
ples/actions.spec.js,cypress/integration/examples/connectors.spec.js,cypress/integration/examples/waiting.spec.js,cypress/integration/examples/utilities.spec.js,cypress/integration/examples/assertions.spec.js,cypress/integration/exa
mples/misc.spec.js,cypress/integration/examples/spies_stubs_clocks.spec.js || exit_code=$? ; pkill -9 cypress ; exit $exit_code'
[-] ~$ timeout --preserve-status 30m docker-compose  -p orchestator_project -f docker-compose.yml run --name container_96489__1 cypress-container bash -c 'exit_code=0; npx cypress run -b chrome --headless --spec cypress/integration/
examples/window.spec.js,cypress/integration/examples/test.spec3.js,cypress/integration/examples/files.spec.js,cypress/integration/examples/test.spec.js,cypress/integration/examples/querying.spec.js,cypress/integration/examples/alias
ing.spec.js,cypress/integration/examples/navigation.spec.js,cypress/integration/examples/network_requests.spec.js,cypress/integration/examples/cypress_api.spec.js,cypress/integration/examples/traversal.spec.js,cypress/integration/ex
amples/viewport.spec.js || exit_code=$? ; pkill -9 cypress ; exit $exit_code'
ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
Type "TIMEOUT /?" for usage.
'exit_code' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
Type "TIMEOUT /?" for usage.
'exit_code' is not recognized as an internal or external command,
operable program or batch file.

[*] Stop the cypress containers

Containers are not starting.

**Comment by 0xIslamTaha** [comment]
@Surajbehera2017 
You r welcome, 

could u post the following details:
- OS 
- screenshots 
- node version

**Comment by Surajbehera2017** [comment]
These are the details:
OS: Windows 10
Node Version: 8.3.1

Console dump:

Windows PowerShell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Cypress\CypressWorkspace\Orchastrator-2\orchestrator-public-use-case> npm i

up to date, audited 305 packages in 5s

39 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (6 moderate, 1 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix
To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
PS C:\Cypress\CypressWorkspace\Orchastrator-2\orchestrator-public-use-case> npx orchestrator --config orchestrator.json

   ██████      ██████       ██████     ██   ██     ███████     ███████     ████████     ██████       █████      ████████      ██████      ██████
  ██    ██     ██   ██     ██          ██   ██     ██          ██             ██        ██   ██     ██   ██        ██        ██    ██     ██   ██
  ██    ██     ██████      ██          ███████     █████       ███████        ██        ██████      ███████        ██        ██    ██     ██████
  ██    ██     ██   ██     ██          ██   ██     ██               ██        ██        ██   ██     ██   ██        ██        ██    ██     ██   ██
   ██████      ██   ██      ██████     ██   ██     ███████     ███████        ██        ██   ██     ██   ██        ██         ██████      ██   ██
                                                                                                                             v 2.1.0 @0xIslamTaha


[*] Checking the requirements
[-] docker is installed ✔️
[-] docker-compose is installed ✔️
[-] timeout is installed ✔️

[*] Overwrite the config file with the arguments if there is any
[*] Export the environment variables

[*] Execute the pre commands
[-] ~$ rm -rf cypress/report/* #Remove the old reports
'rm' is not recognized as an internal or external command,
operable program or batch file.
[-] ~$ mkdir -p mochawesome-report
'exit_code' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
Type "TIMEOUT /?" for usage.
'exit_code' is not recognized as an internal or external command,
operable program or batch file.

[*] Stop the cypress containers
Traceback (most recent call last):                                  
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version           
  File "docker\utils\decorators.py", line 46, in inner        
  File "docker\api\client.py", line 237, in _get              
  File "requests\sessions.py", line 543, in get               
  File "requests\sessions.py", line 530, in request           
  File "requests\sessions.py", line 643, in send              
  File "requests\adapters.py", line 439, in send              
  File "urllib3\connectionpool.py", line 670, in urlopen      
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request                
  File "http\client.py", line 1301, in _send_request          
  File "http\client.py", line 1250, in endheaders             
  File "http\client.py", line 1010, in _send_output           
  File "http\client.py", line 950, in send                    
  File "docker\transport\npipeconn.py", line 32, in connect   
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[18240] Failed to execute script docker-compose

[*] Generate the reports
[-] HTML report: mochawesome-report/mochawesome.html
[-] Execution time report: executionTimeReport/specsExecutionTime.json
[-] chrome
┌─────────┬──────────────────────────────┬──────────┐
│ (index) │           specName           │ duration │
├─────────┼──────────────────────────────┼──────────┤
│    0    │      'location.spec.js'      │  '0:01'  │
│    1    │   'local_storage.spec.js'    │  '0:01'  │
│    2    │       'window.spec.js'       │  '0:01'  │
│    3    │      'cookies.spec.js'       │  '0:02'  │
│    4    │     'connectors.spec.js'     │  '0:02'  │
│    5    │       'files.spec.js'        │  '0:02'  │
│    6    │      'aliasing.spec.js'      │  '0:02'  │
│    7    │    'cypress_api.spec.js'     │  '0:03'  │
│    8    │      'querying.spec.js'      │  '0:03'  │
├─────────┼──────────────────────────────┼──────────┤
│    0    │      'location.spec.js'      │  '0:00'  │
│    1    │   'local_storage.spec.js'    │  '0:00'  │
│    2    │       'window.spec.js'       │  '0:00'  │
│    3    │      'cookies.spec.js'       │  '0:00'  │
│    4    │     'connectors.spec.js'     │  '0:00'  │
│    5    │       'files.spec.js'        │  '0:00'  │
│    6    │      'aliasing.spec.js'      │  '0:00'  │
│    7    │    'cypress_api.spec.js'     │  '0:00'  │
│    8    │      'querying.spec.js'      │  '0:00'  │
│    9    │     'utilities.spec.js'      │  '0:00'  │
│   10    │        'misc.spec.js'        │  '0:00'  │
│   11    │     'navigation.spec.js'     │  '0:00'  │
│   12    │     'assertions.spec.js'     │  '0:00'  │
│   13    │      'viewport.spec.js'      │  '0:00'  │
│   14    │ 'spies_stubs_clocks.spec.js' │  '0:00'  │
│   15    │     'traversal.spec.js'      │  '0:00'  │
│   16    │  'network_requests.spec.js'  │  '0:00'  │
│   17    │      'waiting.spec.js'       │  '0:00'  │
│   18    │      'actions.spec.js'       │  '0:00'  │
└─────────┴──────────────────────────────┴──────────┘

[*] Total execution time: 5.138s
[*] Exit code: 1
PS C:\Cypress\CypressWorkspace\Orchastrator-2\orchestrator-public-use-case>
